name: osm_geocoder
description: Obtain detailed location data without needing an API key. This package is a client for the Open Street Map.
version: 1.0.0
homepage: https://github.com/JosManoel/opm_geocoder
repository: https://github.com/JosManoel/opm_geocoder
issue_tracker: https://github.com/JosManoel/opm_geocoder/issues

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  dartdoc: ^8.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
