name: osm_geocoder
description: Forward, Reverse geocoding and Search Address without any apikey.
version: 1.0.1
homepage: https://github.com/JosManoel/opm_geocoder
repository: https://github.com/JosManoel/opm_geocoder
issue_tracker: https://github.com/JosManoel/opm_geocoder/issues

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  dartdoc: ^8.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
